server {
    listen 9000;
    
    location / {
        root /var/www/html/softy-pinko-front-end;
        index index.html;
    }

    # This routes API requests to the back-end container
    location /api/ {
        proxy_pass http://back-end:5252/api/;
    }
}